VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

# Size optimizations
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = no